---
# tasks file for simplescreenrecorder - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ simplescreenrecorder_app }}
  apt:
    name: "{{ simplescreenrecorder_app }}"
    state: "{{ simplescreenrecorder_desired_state }}"
    force_apt_get: yes
    update_cache: yes
